### ISSUE TITLE
Does not install on windows 7 

### ISSUE THREAD

**Issue by davidhadas** [aflc/editdistance#1]
F:\cordova\zShoppingList>python -m pip install  editdistance
Downloading/unpacking editdistance
  Downloading editdistance-0.2.tar.gz
  Running setup.py (path:c:\users\hadas\appdata\local\temp\pip_build_Hadas\editd
istance\setup.py) egg_info for package editdistance

Installing collected packages: editdistance
  Running setup.py install for editdistance
    building 'editdistance.bycython' extension
    error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat).
Get it from http://aka.ms/vcpython27
    Complete output from command c:\python27\python.exe -c "import setuptools, t
okenize;**file**='c:\users\hadas\appdata\local\temp\pip_build_Hadas\editd
istance\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read()
.replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\hadas\appd
ata\local\temp\pip-fvrg_p-record\install-record.txt --single-version-externally-
managed --compile:
    running install

running build

running build_py

creating build

creating build\lib.win-amd64-2.7

creating build\lib.win-amd64-2.7\editdistance

copying editdistance__init__.py -> build\lib.win-amd64-2.7\editdistance

copying editdistance_editdistance.h -> build\lib.win-amd64-2.7\editdistance

running build_ext

building 'editdistance.bycython' extension

error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat). Get
it from http://aka.ms/vcpython27

---

Cleaning up...
Command c:\python27\python.exe -c "import setuptools, tokenize;**file**='c:\use
rs\hadas\appdata\local\temp\pip_build_Hadas\editdistance\setup.py';exec(c
ompile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), _
_file__, 'exec'))" install --record c:\users\hadas\appdata\local\temp\pip-fvrg_p
-record\install-record.txt --single-version-externally-managed --compile failed
with error code 1 in c:\users\hadas\appdata\local\temp\pip_build_Hadas\editdista
nce
Storing debug log for failure in C:\Users\Hadas\pip\pip.log

**Comment by pombredanne** [comment]
> error: Microsoft Visual C++ 9.0 is required (Unable to find vcvarsall.bat).
Get it from http://aka.ms/vcpython27

did you follow these instructions ?
