### ISSUE TITLE
Can't install editdistance on Python 2.7.5 Linux

### ISSUE THREAD

**Issue by fabiochelly** [aflc/editdistance#11]
With the command pip install editdistance, I get the following error:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-_9A6Oo/editdistance/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kz6UnG-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-_9A6Oo/editdistance/

**Comment by Psy-Fer** [comment]
Could try 
`sudo pip -H install editdistance`
