### ISSUE TITLE
Create binary wheel

### ISSUE THREAD

**Issue by ArneBachmann** [aflc/editdistance#17]
Could you please build and distribute a binary wheel as referenced in #6 so not everyone has to learn building C-code on their Windows machines?
I tend to disregard all pip packages that require setting up development environments on the user machine, I guess others do so as well.
I develop cross-platform software and stuff usually works fine on Linux at first, but when the same pip command on Windows fails I usually get disappointed. Am I crazy?

**Comment by ArneBachmann** [comment]
In the meantime, I will use https://github.com/orsinium/textdistance which supports several functions and is cross-platform. Speed is not the highest priority for me.
Keep up the good work!

**Comment by aflc** [comment]
Sorry for late reply, today I released v0.4, no changes on any sources, but have binary wheels on Linux, OSX, and Windows.
I tested on OSX and Windows, so please try v0.4!

**Comment by ArneBachmann** [comment]
Great news! This installed flawlessly into anaconda and performs fast. Thanks!
