### ISSUE TITLE
AttributeError: module 'editdistance' has no attribute 'eval'

### ISSUE THREAD

**Issue by tyteen4a03** [aflc/editdistance#19]
Running Python 3.6 on Windows 10, installed the module wheel. When I go into the interpreter and try `import editdistance`, it gives me `AttributeError: module 'editdistance' has no attribute 'eval'`.

Does anybody have a similar issue?

**Comment by hi6tanaka** [comment]
Hmm. Please confirm if there is a file or directory which  has the same name "editdistance". Or check your sys.path.

**Comment by tyteen4a03** [comment]
That was... extremely stupid of me.
