### ISSUE TITLE
min() is not defined in _editdistance.cpp

### ISSUE THREAD

**Issue by dancsi** [aflc/editdistance#2]
Hello, the library does not compile on Windows with Visual Studio because `_min()` is not defined. You should add

``` C++
#include <algorithm>
```

to `_editdistance.cpp`, and it will compile normally.

**Comment by pombredanne** [comment]
would this need to be guarded by an ifdef?

**Comment by dancsi** [comment]
I don't think so, since there is no harm is including <algorithm>.
