### ISSUE TITLE
How much memory does it use?

### ISSUE THREAD

**Issue by thomasahle** [aflc/editdistance#20]
I tried finding the edit-distance of some large strings (binary, length 10^6) and the OS ended up killing the process. Does this implementation use quadratic space? In that case, it would be nice to improve it to linear.

**Comment by AMR-KELEG** [comment]
I believe it's also a quadratic space implementation:
https://github.com/aflc/editdistance/blob/master/editdistance/_editdistance.cpp#L67
I am not sure whether there is a way to make it linear without affecting the running time.

**Comment by thomasahle** [comment]
The trick is to keep just two rows of the table. In the inner loop (over j) we are always just referring to the same row (i) or the previous (i-1).
Basically changing dp[i-1] to dp[(i-1)&1] is enough, so there's no performance cost.

**Comment by AMR-KELEG** [comment]
> The trick is to keep just two rows of the table. In the inner loop (over j) we are always just referring to the same row (i) or the previous (i-1).
> Basically changing dp[i-1] to dp[(i-1)&1] is enough, so there's no performance cost.

Ah, my bad.
Yes, that's right.
But do you think that would be beneficial to you given that the running time will still be:`O(len1 * len2) ; len1 is the length of the first string and len2 is the length of the second string`?

**Comment by thomasahle** [comment]
Yes, the running time is fine. That's just waiting. Memory usage is worse as it kills the program.

Thank you a lot of this useful library!

**Comment by aflc** [comment]
Thanks for your contribution!
i'll check it out.
