### ISSUE TITLE
Version 0.5 Linux / Python3 wheels missing

### ISSUE THREAD

**Issue by sdreher** [aflc/editdistance#22]
The newly released `0.5` build does not include wheels for Linux / python3.x (0.4 did include these wheels). Could you please update to include these wheels?

**Comment by aflc** [comment]
Thanks reporting,

https://pypi.org/help/#file-name-reuse

Error with above.

So i will release a new version

**Comment by aflc** [comment]
I can't upload same content again, never :(

**Comment by sdreher** [comment]
Looks good. Thank you!
