### ISSUE TITLE
Provide sdist for redistribution

### ISSUE THREAD

**Issue by sscherfke** [aflc/editdistance#23]
Since the 0.5 release, there are no more source distributions on PyPI. Could you please provide one? This makes it a lot easier to redistribute editdistance (e.g., as conda package or in Linux distributions).

**Comment by aflc** [comment]
Sorry for verrry late reply. 
I just upload the source tar ball.

(c.f. #26)

**Comment by jayvdb** [comment]
Could you include a copy of the license, with any changes needed by the license, such as filling in the (c) `<name>` & `<year range>`

**Comment by aflc** [comment]
I opened a new issue #30.
