### ISSUE TITLE
Release source tarball to PyPI

### ISSUE THREAD

**Issue by sunpoet** [aflc/editdistance#26]
Could you please consider releasing source tarball to PyPI, just like editdistance-0.4.tar.gz?
Thanks!

**Comment by aflc** [comment]
Oh, sorry for that,

https://pypi.org/project/editdistance/#files
https://files.pythonhosted.org/packages/07/61/9fac12e2688bc59d8b6a575e952826d93120e44d8db1bb7fe6c60e6994a1/editdistance-0.5.2.tar.gz

Now sources on PyPI.

**Comment by sunpoet** [comment]
Thank you!
