### ISSUE TITLE
Create tag for v0.3.1

### ISSUE THREAD

**Issue by jayvdb** [aflc/editdistance#29]
openSUSE has been providing 0.3.1 until now.

https://github.com/aflc/editdistance/commit/3ea84a7dd3258c76aa3be851ef3d50e59c886846 is the commit for that one.  Could you add tags for it, and any other versions that you can easily find.

This helps when building a changelog.

**Comment by aflc** [comment]
Thanks your suggestion!

https://github.com/aflc/editdistance/releases/tag/v0.3.1

**Comment by jayvdb** [comment]
Much appreciated
