### ISSUE TITLE
cc1plus related build error on ubuntu 14.04

### ISSUE THREAD

**Issue by sfchen** [aflc/editdistance#3]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I./editdistance -I/usr/include/python3.4m -c editdistance/_editdistance.cpp -o build/temp.linux-x86_64-3.4/editdistance/_editdistance.o

x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by aflc** [comment]
Did you install g++? You need c++ compiler.
Try this: 

```
$ sudo apt-get install g++
```

It's maybe helpful: http://ubuntuforums.org/archive/index.php/t-345201.html

**Comment by sfchen** [comment]
I installed it, sure.

Actually I figured out the reason: the gcc version and g++ version should be the same.

**Comment by aflc** [comment]
OK. So let it close.
