### ISSUE TITLE
Not able to install edidistance on Python 2.7 

### ISSUE THREAD

**Issue by mit2nil** [aflc/editdistance#6]
Hi,

I tried installing using command "pip install editdistance" on my windows 10 machine. 
First it gave error saying can't find vcvarshall.bat and provided url to download it. After installing vcforpython27 from http://www.microsoft.com/en-us/download/details.aspx?id=44266, 

**I am getting following installation error.**

Collecting editdistance
  Using cached editdistance-0.2.tar.gz
Building wheels for collected packages: editdistance
  Running setup.py bdist_wheel for editdistance: started
  Running setup.py bdist_wheel for editdistance: finished with status 'error'
  Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mit2n\appdata\local\temp\pip-build-piojmz\editdistance\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d c:\users\mit2n\appdata\local\temp\tmpx3xgv6pip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\editdistance
  copying editdistance__init__.py -> build\lib.win32-2.7\editdistance
  copying editdistance_editdistance.h -> build\lib.win32-2.7\editdistance
  running build_ext
  building 'editdistance.bycython' extension
  creating build\temp.win32-2.7
  creating build\temp.win32-2.7\Release
  creating build\temp.win32-2.7\Release\editdistance
  C:\Users\mit2n\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./editdistance -Ic:\python27\include -Ic:\python27\PC /Tpeditdistance/_editdistance.cpp /Fobuild\temp.win32-2.7\Release\editdistance/_editdistance.obj
  _editdistance.cpp
  editdistance/_editdistance.cpp(16) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
  error: command 'C:\Users\mit2n\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2

---

  Running setup.py clean for editdistance
Failed to build editdistance
Installing collected packages: editdistance
  Running setup.py install for editdistance: started
    Running setup.py install for editdistance: finished with status 'error'
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mit2n\appdata\local\temp\pip-build-piojmz\editdistance\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mit2n\appdata\local\temp\pip-m6xc_t-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\editdistance
    copying editdistance__init__.py -> build\lib.win32-2.7\editdistance
    copying editdistance_editdistance.h -> build\lib.win32-2.7\editdistance
    running build_ext
    building 'editdistance.bycython' extension
    creating build\temp.win32-2.7
    creating build\temp.win32-2.7\Release
    creating build\temp.win32-2.7\Release\editdistance
    C:\Users\mit2n\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I./editdistance -Ic:\python27\include -Ic:\python27\PC /Tpeditdistance/_editdistance.cpp /Fobuild\temp.win32-2.7\Release\editdistance/_editdistance.obj
    _editdistance.cpp
    editdistance/_editdistance.cpp(16) : fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory
    error: command 'C:\Users\mit2n\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\cl.exe' failed with exit status 2

```
----------------------------------------
```

 Failed building wheel for editdistance
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;**file**='c:\users\mit2n\appdata\local\temp\pip-build-piojmz\editdistance\setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record c:\users\mit2n\appdata\local\temp\pip-m6xc_t-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\mit2n\appdata\local\temp\pip-build-piojmz\editdistance

**Comment by jgonggrijp** [comment]
The package relies on `stdint.h`, which MSVC doesn't (always) provide. However, this can be fixed by copying it into the source directory from [msinttypes.googlecode.com](http://msinttypes.googlecode.com/svn/trunk/stdint.h). I was able to get the package installed and functional by doing just that. There is also [a portable version from Paul Hsieh](http://www.azillionmonkeys.com/qed/pstdint.h).

Ideally, the `editdistance` package should include the latter header. However, the software appears to be unmaintained. I will look into options for providing a new package that includes the fix.

**Comment by mit2nil** [comment]
Thanks jgonggrijp. it installed correctly after manually putting the file. It would be great if these dependencies were mentioned in the readme.md

**Comment by aflc** [comment]
I released a new release 0.3.1, it does not required stdint.h any more  on Windows/VS2010. So please try this.
